version: "2.2"
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
  ccvg:
    build: ./
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    restart: always
